language: scala
jdk:
  - openjdk8
  - openjdk11
scala:
  - 2.11.12
  - 2.12.8
  - 2.13.0
script:
  - sbt ++$TRAVIS_SCALA_VERSION test
cache:
  directories:
  - $HOME/.ivy2
  - $HOME/.sbt/boot
  - $HOME/.sbt/launchers
