version: ~> 1.0 # needed for imports
import: scala/scala-dev:travis/default.yml

language: scala

env:
  - ADOPTOPENJDK=8
  - ADOPTOPENJDK=11
scala:
  - 2.12.12
  - 2.13.3

script:
  - sbt ++$TRAVIS_SCALA_VERSION test
