# opt-in to Travis new infrastructure
sudo: false

# cache stuff, hopefully shortening build times
cache:
  directories:
  - $HOME/.ivy2
  - $HOME/.sbt/boot
  - $HOME/.sbt/launchers

jdk:
  - oraclejdk8
  - openjdk11
language: scala
scala:
  - 2.11.12
  - 2.12.8
  - 2.13.0-RC1

script:
  - sbt ++$TRAVIS_SCALA_VERSION test
