language: scala

jdk:
  - openjdk8
  - openjdk11
scala:
  - 2.12.10
  - 2.13.1

script:
  - sbt ++$TRAVIS_SCALA_VERSION test

cache:
  directories:
  - $HOME/.sbt/boot
  - $HOME/.sbt/launchers
  - $HOME/.ivy2
  - $HOME/.coursier/cache
before_cache:
  - find $HOME/.sbt -name "*.lock" | xargs rm
  - find $HOME/.ivy2 -name "ivydata-*.properties" | xargs rm
